// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQFqihsK8n9_q8ry3lp4_ZaEXkE66FpL0',
    appId: '1:89447583523:ios:393a2730d8fc2bdb9c0696',
    messagingSenderId: '89447583523',
    projectId: 'scn-app-a784e',
    storageBucket: 'scn-app-a784e.firebasestorage.app',
    iosBundleId: 'com.example.scnApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQFqihsK8n9_q8ry3lp4_ZaEXkE66FpL0',
    appId: '1:89447583523:ios:393a2730d8fc2bdb9c0696',
    messagingSenderId: '89447583523',
    projectId: 'scn-app-a784e',
    storageBucket: 'scn-app-a784e.firebasestorage.app',
    iosBundleId: 'com.example.scnApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBunPyO0WZAHyJ-B3f-j7t0B_OXzWwIKUE',
    appId: '1:89447583523:web:d4cc7ddb819c84af9c0696',
    messagingSenderId: '89447583523',
    projectId: 'scn-app-a784e',
    authDomain: 'scn-app-a784e.firebaseapp.com',
    storageBucket: 'scn-app-a784e.firebasestorage.app',
    measurementId: 'G-HR6BCRWQFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHkW9VrPoAc9r1teGhK13tofllhfuNWTQ',
    appId: '1:89447583523:android:e3995f31b675ea229c0696',
    messagingSenderId: '89447583523',
    projectId: 'scn-app-a784e',
    storageBucket: 'scn-app-a784e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBunPyO0WZAHyJ-B3f-j7t0B_OXzWwIKUE',
    appId: '1:89447583523:web:02807c142d0ac7a59c0696',
    messagingSenderId: '89447583523',
    projectId: 'scn-app-a784e',
    authDomain: 'scn-app-a784e.firebaseapp.com',
    storageBucket: 'scn-app-a784e.firebasestorage.app',
    measurementId: 'G-4E4TL0EEKZ',
  );

}